/* SPDX-License-Identifier: MIT */
/* A code generator built by this same build: reads any number of .def files
 * and writes one C source listing what it found. Stands in for the real
 * thing -- an IDL compiler, a resource packer, a definition-language
 * front end. */

#include <stdio.h>
#include <string.h>

int main(int argc, char **argv) {
    if (argc < 3) {
        fprintf(stderr, "usage: %s <output.c> <input.def>...\n", argv[0]);
        return 2;
    }

    FILE *out = fopen(argv[1], "w");
    if (!out) {
        perror(argv[1]);
        return 1;
    }

    fprintf(out, "/* generated by collate -- do not edit */\n");
    fprintf(out, "const char *const entries[] = {\n");

    int count = 0;
    for (int i = 2; i < argc; i++) {
        FILE *in = fopen(argv[i], "r");
        if (!in) {
            perror(argv[i]);
            fclose(out);
            return 1;
        }
        char line[256];
        while (fgets(line, sizeof line, in)) {
            line[strcspn(line, "\r\n")] = '\0';
            if (line[0] == '\0' || line[0] == '#') continue;
            fprintf(out, "    \"%s\",\n", line);
            count++;
        }
        fclose(in);
    }

    fprintf(out, "};\n");
    fprintf(out, "const int entry_count = %d;\n", count);
    fclose(out);
    return 0;
}
