// SPDX-License-Identifier: MIT
#include "mainwindow.h"

#include <QFile>
#include <QLabel>
#include <QTextStream>

#include "ui_mainwindow.h"  // generated by uic from mainwindow.ui

MainWindow::MainWindow(QWidget *parent)
    : QMainWindow(parent), ui(new Ui::MainWindow) {
    ui->setupUi(this);
    connect(this, &MainWindow::checked, this, &MainWindow::onChecked);
}

MainWindow::~MainWindow() { delete ui; }

void MainWindow::onChecked(const QString &message) { m_lastMessage = message; }

bool MainWindow::selfCheck() {
    QTextStream out(stdout);

    // From the Designer form (ui_mainwindow.h).
    out << "label: " << ui->greetingLabel->text() << "\n";

    // From the compiled-in resources (qrc_resources.cpp).
    QFile message(":/assets/message.txt");
    if (!message.open(QIODevice::ReadOnly | QIODevice::Text)) {
        out << "resource missing!\n";
        return false;
    }
    out << "resource: " << QString::fromUtf8(message.readAll()).trimmed() << "\n";

    // Through the meta-object system (moc_mainwindow.cpp).
    emit checked(QStringLiteral("signals ok"));
    out << "signal: " << m_lastMessage << "\n";

    return !ui->greetingLabel->text().isEmpty() && m_lastMessage == "signals ok";
}
