// SPDX-License-Identifier: MIT
// A QObject with signals/slots: its meta-object code comes from
// moc_counter.cpp, generated by env.qt.Moc() and compiled as its own TU.
#pragma once

#include <QObject>

class Counter : public QObject {
    Q_OBJECT
public:
    explicit Counter(QObject *parent = nullptr) : QObject(parent) {}
    int value() const { return m_value; }

public slots:
    void increment();

signals:
    void valueChanged(int newValue);

private:
    int m_value = 0;
};
