# SPDX-License-Identifier: MIT
"""LaTeX build helper for pcons.

Wraps latexmk for multi-pass LaTeX compilation and converts the .fls
(file recorder) output to a Ninja-compatible depfile.

Usage (invoked by pcons-generated Ninja rules):
    python -m pcons.util.latex_deps --engine pdflatex --depfile out.d -o out.pdf src.tex

This script:
1. Runs latexmk with the chosen engine and -recorder flag
2. Parses the resulting .fls file to find all input dependencies
3. Writes a Ninja depfile so incremental rebuilds track \\input/\\include files
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
from pathlib import Path, PurePosixPath

# Extensions for intermediate files that should NOT appear in the depfile.
# These are generated by LaTeX/BibTeX/makeindex and are not user sources.
_INTERMEDIATE_EXTS = frozenset(
    {
        ".aux",
        ".bbl",
        ".blg",
        ".fdb_latexmk",
        ".fls",
        ".idx",
        ".ilg",
        ".ind",
        ".lof",
        ".log",
        ".lot",
        ".nav",
        ".out",
        ".snm",
        ".toc",
        ".vrb",
    }
)


def _collect_fls_deps(fls_path: Path) -> list[str]:
    """Extract input dependencies from a .fls file.

    The .fls file (generated by ``-recorder``) lists files read by the TeX
    engine.  This does NOT include files read by BibTeX — those come from
    the ``.fdb_latexmk`` file instead.
    """
    deps: list[str] = []
    seen: set[str] = set()

    try:
        with open(fls_path) as f:
            for line in f:
                line = line.strip()
                if not line.startswith("INPUT "):
                    continue
                path = line[6:]  # strip "INPUT "
                ext = PurePosixPath(path).suffix.lower()
                if ext in _INTERMEDIATE_EXTS:
                    continue
                if path in seen:
                    continue
                seen.add(path)
                deps.append(path.replace("\\", "/"))
    except FileNotFoundError:
        pass

    return deps


def _collect_fdb_deps(fdb_path: Path) -> list[str]:
    """Extract additional dependencies from latexmk's .fdb_latexmk file.

    This captures files that BibTeX reads (e.g., ``.bib``, ``.bst`` files)
    which are not recorded in the ``.fls`` file.

    The .fdb_latexmk format has lines like::

        "/path/to/refs.bib" 1775424615.20727 138 aec0009dc... ""

    We extract quoted file paths and filter to user-source extensions.
    """
    # Extensions we want from the fdb file (BibTeX-related inputs)
    bib_exts = frozenset({".bib", ".bst"})

    deps: list[str] = []
    try:
        with open(fdb_path) as f:
            for line in f:
                line = line.strip()
                if not line.startswith('"'):
                    continue
                # Extract quoted path
                end = line.find('"', 1)
                if end < 0:
                    continue
                path = line[1:end]
                ext = PurePosixPath(path).suffix.lower()
                if ext in bib_exts:
                    deps.append(path.replace("\\", "/"))
    except FileNotFoundError:
        pass

    return deps


def fls_to_depfile(fls_path: Path, depfile_path: Path, target: str) -> None:
    """Convert LaTeX dependency files to a Ninja-compatible depfile.

    Combines dependencies from:
    - The ``.fls`` file (TeX engine inputs: .tex, .sty, .cls, fonts, etc.)
    - The ``.fdb_latexmk`` file (BibTeX inputs: .bib, .bst files)

    Args:
        fls_path: Path to the .fls file.
        depfile_path: Path to write the depfile.
        target: The target name to use in the depfile (e.g., ``paper.pdf``).
    """
    deps = _collect_fls_deps(fls_path)

    # Also collect BibTeX deps from latexmk's database
    fdb_path = fls_path.with_suffix(".fdb_latexmk")
    bib_deps = _collect_fdb_deps(fdb_path)

    # Merge, deduplicating
    seen = set(deps)
    for dep in bib_deps:
        if dep not in seen:
            seen.add(dep)
            deps.append(dep)

    with open(depfile_path, "w") as f:
        f.write(f"{target}:")
        for dep in deps:
            escaped = dep.replace(" ", "\\ ")
            f.write(f" \\\n  {escaped}")
        f.write("\n")


def run_latexmk(
    source: str,
    output: str,
    *,
    engine: str = "pdflatex",
    latexmk_cmd: str = "latexmk",
    depfile: str | None = None,
    extra_flags: list[str] | None = None,
) -> int:
    """Run latexmk and optionally convert dependencies.

    Args:
        source: Path to the main .tex file.
        output: Path to the output PDF.
        engine: LaTeX engine (pdflatex, xelatex, lualatex).
        latexmk_cmd: The latexmk command.
        depfile: If set, convert .fls to this depfile path after building.
        extra_flags: Additional flags passed through to latexmk.

    Returns:
        latexmk exit code.
    """
    output_dir = str(Path(output).parent)

    # Build the latexmk command
    cmd = [latexmk_cmd]

    # Engine selection
    if engine == "xelatex":
        cmd.append("-xelatex")
    elif engine == "lualatex":
        cmd.append("-lualatex")
    else:
        cmd.append("-pdf")

    cmd.extend(
        [
            "-interaction=nonstopmode",
            "-recorder",
            f"-output-directory={output_dir}",
        ]
    )

    if extra_flags:
        cmd.extend(extra_flags)

    cmd.append(source)

    # Set TEXINPUTS and BIBINPUTS so LaTeX can find files relative to the
    # source directory (not just the build/output directory).
    source_dir = str(Path(source).resolve().parent)
    env = os.environ.copy()
    sep = os.pathsep
    for var in ("TEXINPUTS", "BIBINPUTS", "BSTINPUTS"):
        existing = env.get(var, "")
        # Append source dir; trailing separator means "also search defaults"
        env[var] = f"{source_dir}{sep}{existing}"

    # Run latexmk
    result = subprocess.run(cmd, env=env)

    # Convert .fls to depfile if requested
    if depfile is not None and result.returncode == 0:
        # The .fls file is in the output directory with the source basename
        source_stem = Path(source).stem
        fls_path = Path(output_dir) / f"{source_stem}.fls"
        fls_to_depfile(fls_path, Path(depfile), output.replace("\\", "/"))

    return result.returncode


def main() -> None:
    """CLI entry point for ``python -m pcons.util.latex_deps``."""
    parser = argparse.ArgumentParser(
        description="Run latexmk and generate Ninja depfile from .fls output",
    )
    parser.add_argument(
        "--engine",
        default="pdflatex",
        choices=["pdflatex", "xelatex", "lualatex"],
        help="LaTeX engine (default: pdflatex)",
    )
    parser.add_argument(
        "--latexmk",
        default="latexmk",
        help="latexmk command (default: latexmk)",
    )
    parser.add_argument(
        "--depfile",
        help="Write Ninja depfile to this path",
    )
    parser.add_argument(
        "-o",
        "--output",
        required=True,
        help="Output PDF path",
    )
    parser.add_argument(
        "source",
        help="Input .tex file",
    )
    parser.add_argument(
        "extra",
        nargs="*",
        help="Additional flags passed to latexmk",
    )

    args = parser.parse_args()

    # Ensure output directory exists
    os.makedirs(Path(args.output).parent, exist_ok=True)

    rc = run_latexmk(
        args.source,
        args.output,
        engine=args.engine,
        latexmk_cmd=args.latexmk,
        depfile=args.depfile,
        extra_flags=args.extra or None,
    )
    sys.exit(rc)


if __name__ == "__main__":
    main()
