# SPDX-License-Identifier: MIT
"""Build-time helper: capture compiler-predefined macros for moc.

moc evaluates preprocessor conditionals while parsing, but knows none of
the compiler's built-in macros (``__linux__``, ``__cplusplus``, ...), so
platform-guarded ``Q_OBJECT`` declarations can be mis-parsed. The fix —
same as CMake's AUTOMOC — is a ``moc_predefs.h`` generated by the real
compiler and handed to moc via ``--include``.

Invoked as a build edge (GCC/Clang style compilers only; on MSVC moc's
``--compiler-flavor msvc`` covers the essentials instead):

    python -m pcons.toolchains.qt._moc_predefs --cxx <compiler> -o <out> [flags...]

The output is only rewritten when its content changes, so with ninja's
``restat`` the downstream moc edges re-run only on real macro changes.
"""

from __future__ import annotations

# argparse, not click: this runs under $qt.python, which the user may point
# at an interpreter that has no pcons, and so no click, installed.
import argparse
import subprocess
import sys
from pathlib import Path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cxx", required=True, help="C++ compiler command")
    parser.add_argument("-o", "--output", required=True, help="Output header path")
    # Anything unrecognized is a compiler flag (-std=..., --target=...);
    # they affect the predefined-macro set and pass through verbatim.
    args, flags = parser.parse_known_args(argv)

    cmd = [args.cxx, *flags, "-x", "c++", "-dM", "-E", "-"]
    try:
        result = subprocess.run(
            cmd, input="", capture_output=True, text=True, timeout=60
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        print(f"moc_predefs: failed to run {args.cxx}: {exc}", file=sys.stderr)
        return 1
    if result.returncode != 0:
        print(
            f"moc_predefs: {args.cxx} -dM -E failed:\n{result.stderr}",
            file=sys.stderr,
        )
        return 1

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    # Rewrite only on change: with ninja restat, downstream moc edges
    # then re-run only when the macro set actually changed.
    if not output.exists() or output.read_text(encoding="utf-8") != result.stdout:
        output.write_text(result.stdout, encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main())
