// C++ calling Swift: the header is generated by the Swift compile
// (-emit-clang-header) into the propagated swiftmodules/ include dir.
#include "Analyzer-Swift.h"

#include <iostream>

int main() {
    double m = Analyzer::scaledMean(3.0, 5.0, 10.0);
    std::cout << "scaled mean = " << m << "\n";
    return 0;
}
