# SPDX-License-Identifier: MIT
"""Generate typed-stub mixin classes for pcons's dynamic-attribute classes.

Two pcons classes use `__getattr__` for dispatch and lose static type
checking as a result:

  - `Project`: builders (Program, StaticLibrary, ...) registered through
    `BuilderRegistry`. Stub lives at `pcons/core/_project_builder_stubs.py`
    and is fully introspected from the registry.

  - `Environment`: tool namespaces (cc, cxx, link, install, archive, ...)
    populated by toolchains and standalone tools. Stub lives at
    `pcons/core/_environment_stubs.py`. There is no single runtime
    registry of tool names — each toolchain installs its own set into
    `env._tools`. The tool list is therefore hardcoded here. See
    `_ENVIRONMENT_TOOL_NAMES` for how to extend; the freshness test only
    catches drift between the generator output and the committed file,
    not omissions in the hardcoded list itself.

The mixin classes are inherited only under `TYPE_CHECKING`; at runtime
the base class is `object` and the original `__getattr__` dispatches as
before.

Usage:
    python -m pcons._gen_stubs              # rewrite all stub files
    python -m pcons._gen_stubs --check      # exit 1 if any file is stale
    python -m pcons._gen_stubs --print      # write all to stdout
"""

from __future__ import annotations

import argparse
import inspect
import sys
from collections.abc import Callable
from inspect import Parameter
from pathlib import Path

from pcons.builders import register_builtin_builders
from pcons.core.builder_registry import BuilderRegistry


def _stub_targets() -> dict[str, Callable[[], str]]:
    """Map of relative path under pcons/ → function that produces the file content."""
    return {
        "core/_project_builder_stubs.py": generate_project_builder_stubs,
        "core/_environment_stubs.py": generate_environment_stubs,
    }


# Annotation names that need rewriting because `Environment` is conventionally
# imported as `Env` in pcons code (and we want the stub to match).
_ANNOTATION_ALIASES = {"Environment": "Env"}

# Parameters dropped from generated stubs (auto-captured at the call site).
_DROPPED_PARAMS = {"defined_at"}


def _rewrite_annotation(anno: str) -> str:
    """Rewrite a string annotation to match the stub file's local names."""
    import re

    out = anno
    for src, dst in _ANNOTATION_ALIASES.items():
        out = re.sub(rf"\b{re.escape(src)}\b", dst, out)
    return out


def _format_param(p: Parameter) -> str:
    """Render a Parameter to its source-level spelling."""
    if p.kind is Parameter.VAR_POSITIONAL:
        return f"*{p.name}"
    if p.kind is Parameter.VAR_KEYWORD:
        return f"**{p.name}"

    parts = [p.name]
    if p.annotation is not Parameter.empty:
        parts.append(f": {_rewrite_annotation(str(p.annotation))}")
    if p.default is not Parameter.empty:
        parts.append(f" = {p.default!r}")
    return "".join(parts)


def _format_method(
    name: str, description: str, params: list[Parameter], ret: str
) -> str:
    """Format one typed method inside `class _ProjectBuilders` (8-space indent)."""
    lines: list[str] = []
    lines.append(f"        def {name}(")
    lines.append("            self,")

    saw_kw_only = False
    seen_positional = False
    for p in params:
        if p.kind in (Parameter.POSITIONAL_OR_KEYWORD, Parameter.POSITIONAL_ONLY):
            seen_positional = True
        if p.kind is Parameter.KEYWORD_ONLY and not saw_kw_only and seen_positional:
            lines.append("            *,")
            saw_kw_only = True
        if p.kind is Parameter.VAR_POSITIONAL:
            saw_kw_only = True
        lines.append(f"            {_format_param(p)},")

    lines.append(f"        ) -> {_rewrite_annotation(ret)}:")
    if description:
        lines.append(f'            """{description}"""')
    lines.append("            ...")
    return "\n".join(lines)


def _owner_of(create_target_fn: object) -> type | None:
    """Return the class that owns `create_target` if there is one.

    `@builder` is applied to a class with `create_target` as a staticmethod;
    in that case we recover the class for its docstring. Builders registered
    directly via `BuilderRegistry.register(create_target=<plain function>)`
    have no owning class, so we return None and let the caller fall back.
    """
    qualname = getattr(create_target_fn, "__qualname__", "")
    module = getattr(create_target_fn, "__module__", "")
    if "." in qualname and module:
        cls_name = qualname.rsplit(".", 1)[0]
        mod = sys.modules.get(module)
        if mod is not None:
            cls = getattr(mod, cls_name, None)
            if isinstance(cls, type):
                return cls
    return None


_PROJECT_FILE_HEADER = '''\
# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for Project's built-in builder methods.

GENERATED by `python -m pcons._gen_stubs` from the BuilderRegistry. Do
not edit by hand — re-run the generator instead.

`Project` inherits from `_ProjectBuilders` only under TYPE_CHECKING (see
project.py). At runtime, `_ProjectBuilders = object` and builder lookup
falls through to `Project.__getattr__` as before. The methods here exist
solely so that type checkers (ty, pyright, mypy) can flag typos like
`project.Programx(...)` and provide completion. User-registered
`@builder` targets are not in this file and remain typed as `Any`.

The class body is nested under `if TYPE_CHECKING:` so that ty does not
treat the `def Foo(...) -> Target: ...` empty bodies as runtime errors;
type checkers see the declarations, runtime never executes them.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pcons.core.environment import Environment as Env
    from pcons.core.node import FileNode, Node
    from pcons.core.target import Target
    from pcons.tools.archive import ArchiveTarget

    class _ProjectBuilders:
        """Typed builder methods for Project (TYPE_CHECKING-only mixin)."""

'''


def generate_project_builder_stubs() -> str:
    """Produce the full content of `_project_builder_stubs.py`."""
    register_builtin_builders()
    parts: list[str] = [_PROJECT_FILE_HEADER]

    methods: list[str] = []
    for name, reg in sorted(BuilderRegistry.all().items()):
        sig = inspect.signature(reg.create_target)
        params = list(sig.parameters.values())[1:]  # drop leading `project`
        params = [p for p in params if p.name not in _DROPPED_PARAMS]
        ret = str(sig.return_annotation)

        description = ""
        owner = _owner_of(reg.create_target)
        if owner is not None and owner.__doc__:
            description = owner.__doc__.strip().splitlines()[0]
        if not description and reg.description:
            description = reg.description
        if reg.platforms:
            description = f"{description} [{'/'.join(reg.platforms)} only]".strip()

        methods.append(_format_method(name, description, params, ret))

    parts.append("\n\n".join(methods))
    parts.append("\n")
    return "".join(parts)


# Well-known tool namespaces registered on Environment by toolchains and
# standalone tools. Unlike Project's builders, there is no single runtime
# registry — each toolchain populates `env._tools` from its own list. Keep
# this in sync when adding a tool to a toolchain's setup; group by source
# so it's easy to audit.
_ENVIRONMENT_TOOL_NAMES: tuple[tuple[str, str], ...] = (
    # name, comment-source
    ("cc", "C/C++ toolchains (gcc, llvm, msvc, clang_cl, emscripten, wasi)"),
    ("cxx", "C/C++ toolchains"),
    ("ar", "GCC/LLVM/emscripten/wasi/gfortran"),
    ("link", "all C/C++ and Fortran toolchains"),
    ("lib", "MSVC and clang-cl"),
    ("rc", "MSVC and clang-cl (Windows resource compiler)"),
    ("ml", "MSVC and clang-cl (assembler)"),
    ("mt", "MSVC (manifest tool)"),
    ("metal", "LLVM on macOS (Apple Metal shader compiler)"),
    ("fc", "gfortran"),
    ("cuda", "CUDA toolchain (added via env.add_toolchain)"),
    ("cython", "Cython toolchain"),
    ("cycc", "Cython toolchain"),
    ("cylink", "Cython toolchain"),
    ("install", "always set up via Environment._setup_standalone_tools"),
    ("archive", "always set up via Environment._setup_standalone_tools"),
)

# Well-known Environment instance variables (initialized in Environment.__init__).
# Unlike tool namespaces, these are real attribute reads, not `_tools` lookups.
_ENVIRONMENT_VAR_TYPES: tuple[tuple[str, str], ...] = (
    ("build_dir", "Path"),
    ("variant", "str"),
)


def generate_environment_stubs() -> str:
    """Produce the full content of `_environment_stubs.py`."""
    lines: list[str] = [
        "# SPDX-License-Identifier: MIT",
        "# ruff: noqa",
        "# fmt: off",
        '"""Typed stub declarations for Environment\'s tool namespaces and known variables.',
        "",
        "GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.",
        "",
        "Each toolchain registers its own subset of tools into `env._tools` at",
        "setup time; there is no single runtime registry to introspect. The",
        "tool list is therefore maintained in `_gen_stubs.py`. Adding a new",
        "tool to a toolchain requires updating `_ENVIRONMENT_TOOL_NAMES` there.",
        "",
        "Environment.__getattr__ is intentionally left visible to type checkers",
        "(returning `Any`), so user-defined cross-tool variables like",
        "`env.my_flag = ...` continue to work without a type:ignore. Known names",
        "below are typed more specifically and take precedence.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from pathlib import Path",
        "from typing import TYPE_CHECKING",
        "",
        "if TYPE_CHECKING:",
        "    from pcons.core.toolconfig import ToolConfig",
        "",
        "    class _EnvironmentStubs:",
        '        """Typed mixin for Environment (TYPE_CHECKING-only)."""',
        "",
    ]
    for tool, source in _ENVIRONMENT_TOOL_NAMES:
        lines.append(f"        {tool}: ToolConfig  # {source}")
    lines.append("")
    for var, typ in _ENVIRONMENT_VAR_TYPES:
        lines.append(f"        {var}: {typ}")
    lines.append("")
    return "\n".join(lines)


def _stub_file_path(relpath: str) -> Path:
    return Path(__file__).resolve().parent / relpath


def write_or_check(mode: str) -> int:
    targets = _stub_targets()
    rc = 0
    for relpath, producer in targets.items():
        new_content = producer()
        if mode == "print":
            sys.stdout.write(f"# === {relpath} ===\n")
            sys.stdout.write(new_content)
            sys.stdout.write("\n")
            continue

        path = _stub_file_path(relpath)
        current = path.read_text() if path.exists() else ""

        if mode == "check":
            if current != new_content:
                sys.stderr.write(
                    f"{path} is out of date with generated stubs.\n"
                    f"Run: python -m pcons._gen_stubs\n"
                )
                rc = 1
        elif mode == "write":
            if current != new_content:
                path.write_text(new_content)
                print(f"Updated {path}")
            else:
                print(f"{path} is up to date.")
        else:
            raise ValueError(f"unknown mode: {mode}")
    return rc


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true", help="Fail if file is stale")
    g.add_argument("--print", action="store_true", help="Print to stdout")
    args = ap.parse_args(argv)
    mode = "check" if args.check else "print" if args.print else "write"
    return write_or_check(mode)


if __name__ == "__main__":
    sys.exit(main())
