# SPDX-License-Identifier: MIT
"""Generate typed builder method stubs for the Project class.

Builders register at runtime via `BuilderRegistry`, dispatched through
`Project.__getattr__`. That dispatch returns `Any`, so type checkers
cannot catch typos like `project.Programx(...)`. To fix that without
duplicating signatures by hand, this module introspects every registered
`create_target` and writes a typed-stub mixin class to
`pcons/core/_project_builder_stubs.py`. `Project` inherits from it under
`TYPE_CHECKING` only; at runtime it inherits from `object` and
`__getattr__` handles dispatch as before.

Usage:
    python -m pcons._gen_stubs              # rewrite the stub file
    python -m pcons._gen_stubs --check      # exit 1 if file is stale
    python -m pcons._gen_stubs --print      # write to stdout
"""

from __future__ import annotations

import argparse
import inspect
import sys
from inspect import Parameter
from pathlib import Path

from pcons.builders import register_builtin_builders
from pcons.core.builder_registry import BuilderRegistry

STUB_FILE_RELPATH = "core/_project_builder_stubs.py"

# Annotation names that need rewriting because `Environment` is conventionally
# imported as `Env` in pcons code (and we want the stub to match).
_ANNOTATION_ALIASES = {"Environment": "Env"}

# Parameters dropped from generated stubs (auto-captured at the call site).
_DROPPED_PARAMS = {"defined_at"}


def _rewrite_annotation(anno: str) -> str:
    """Rewrite a string annotation to match the stub file's local names."""
    import re

    out = anno
    for src, dst in _ANNOTATION_ALIASES.items():
        out = re.sub(rf"\b{re.escape(src)}\b", dst, out)
    return out


def _format_param(p: Parameter) -> str:
    """Render a Parameter to its source-level spelling."""
    if p.kind is Parameter.VAR_POSITIONAL:
        return f"*{p.name}"
    if p.kind is Parameter.VAR_KEYWORD:
        return f"**{p.name}"

    parts = [p.name]
    if p.annotation is not Parameter.empty:
        parts.append(f": {_rewrite_annotation(str(p.annotation))}")
    if p.default is not Parameter.empty:
        parts.append(f" = {p.default!r}")
    return "".join(parts)


def _format_method(
    name: str, description: str, params: list[Parameter], ret: str
) -> str:
    """Format one typed method inside `class _ProjectBuilders` (8-space indent)."""
    lines: list[str] = []
    lines.append(f"        def {name}(")
    lines.append("            self,")

    saw_kw_only = False
    seen_positional = False
    for p in params:
        if p.kind in (Parameter.POSITIONAL_OR_KEYWORD, Parameter.POSITIONAL_ONLY):
            seen_positional = True
        if p.kind is Parameter.KEYWORD_ONLY and not saw_kw_only and seen_positional:
            lines.append("            *,")
            saw_kw_only = True
        if p.kind is Parameter.VAR_POSITIONAL:
            saw_kw_only = True
        lines.append(f"            {_format_param(p)},")

    lines.append(f"        ) -> {_rewrite_annotation(ret)}:")
    if description:
        lines.append(f'            """{description}"""')
    lines.append("            ...")
    return "\n".join(lines)


def _owner_of(create_target_fn: object) -> type | None:
    """Return the class that owns `create_target` if there is one.

    `@builder` is applied to a class with `create_target` as a staticmethod;
    in that case we recover the class for its docstring. Builders registered
    directly via `BuilderRegistry.register(create_target=<plain function>)`
    have no owning class, so we return None and let the caller fall back.
    """
    qualname = getattr(create_target_fn, "__qualname__", "")
    module = getattr(create_target_fn, "__module__", "")
    if "." in qualname and module:
        cls_name = qualname.rsplit(".", 1)[0]
        mod = sys.modules.get(module)
        if mod is not None:
            cls = getattr(mod, cls_name, None)
            if isinstance(cls, type):
                return cls
    return None


_FILE_HEADER = '''\
# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for Project's built-in builder methods.

GENERATED by `python -m pcons._gen_stubs` from the BuilderRegistry. Do
not edit by hand — re-run the generator instead.

`Project` inherits from `_ProjectBuilders` only under TYPE_CHECKING (see
project.py). At runtime, `_ProjectBuilders = object` and builder lookup
falls through to `Project.__getattr__` as before. The methods here exist
solely so that type checkers (ty, pyright, mypy) can flag typos like
`project.Programx(...)` and provide completion. User-registered
`@builder` targets are not in this file and remain typed as `Any`.

The class body is nested under `if TYPE_CHECKING:` so that ty does not
treat the `def Foo(...) -> Target: ...` empty bodies as runtime errors;
type checkers see the declarations, runtime never executes them.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pcons.core.environment import Environment as Env
    from pcons.core.node import FileNode, Node
    from pcons.core.target import Target
    from pcons.tools.archive import ArchiveTarget

    class _ProjectBuilders:
        """Typed builder methods for Project (TYPE_CHECKING-only mixin)."""

'''


def generate_stub_file_content() -> str:
    """Produce the full content of `_project_builder_stubs.py`."""
    register_builtin_builders()
    parts: list[str] = [_FILE_HEADER]

    methods: list[str] = []
    for name, reg in sorted(BuilderRegistry.all().items()):
        sig = inspect.signature(reg.create_target)
        params = list(sig.parameters.values())[1:]  # drop leading `project`
        params = [p for p in params if p.name not in _DROPPED_PARAMS]
        ret = str(sig.return_annotation)

        description = ""
        owner = _owner_of(reg.create_target)
        if owner is not None and owner.__doc__:
            description = owner.__doc__.strip().splitlines()[0]
        if not description and reg.description:
            description = reg.description
        if reg.platforms:
            description = f"{description} [{'/'.join(reg.platforms)} only]".strip()

        methods.append(_format_method(name, description, params, ret))

    parts.append("\n\n".join(methods))
    parts.append("\n")
    return "".join(parts)


def _stub_file_path() -> Path:
    return Path(__file__).resolve().parent / STUB_FILE_RELPATH


def write_or_check(mode: str) -> int:
    new_content = generate_stub_file_content()
    if mode == "print":
        sys.stdout.write(new_content)
        return 0

    path = _stub_file_path()
    current = path.read_text() if path.exists() else ""

    if mode == "check":
        if current != new_content:
            sys.stderr.write(
                f"{path} is out of date with generated builder stubs.\n"
                f"Run: python -m pcons._gen_stubs\n"
            )
            return 1
        return 0
    if mode == "write":
        if current != new_content:
            path.write_text(new_content)
            print(f"Updated {path}")
        else:
            print(f"{path} is up to date.")
        return 0
    raise ValueError(f"unknown mode: {mode}")


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--check", action="store_true", help="Fail if file is stale")
    g.add_argument("--print", action="store_true", help="Print to stdout")
    args = ap.parse_args(argv)
    mode = "check" if args.check else "print" if args.print else "write"
    return write_or_check(mode)


if __name__ == "__main__":
    sys.exit(main())
