/* SPDX-License-Identifier: MIT
 *
 * A generator that only works when run from the source root: it finds its
 * input at the fixed relative path "data/items.txt", and takes the file to
 * write as its only argument. Plenty of real generators are like this --
 * ported from a build system that ran everything from the top of the tree.
 *
 * It also rewrites its output every run, whatever the input said, which is
 * what write_if_different= is for on the pcons side.
 */

#include <stdio.h>
#include <string.h>

#define INPUT "data/items.txt"

int main(int argc, char **argv) {
    FILE *in, *out;
    char line[256];
    int count = 0;

    if (argc != 2) {
        fprintf(stderr, "usage: %s <output.c>\n", argv[0]);
        return 2;
    }

    in = fopen(INPUT, "r");
    if (in == NULL) {
        fprintf(stderr, "make-items: cannot open %s from this directory\n", INPUT);
        return 1;
    }
    out = fopen(argv[1], "w");
    if (out == NULL) {
        fprintf(stderr, "make-items: cannot write %s\n", argv[1]);
        fclose(in);
        return 1;
    }

    fprintf(out, "/* generated by make-items -- do not edit */\n");
    fprintf(out, "const char *const items[] = {\n");
    while (fgets(line, sizeof line, in) != NULL) {
        line[strcspn(line, "\r\n")] = '\0';
        if (line[0] == '\0') {
            continue;
        }
        fprintf(out, "    \"%s\",\n", line);
        count++;
    }
    fprintf(out, "};\n");
    fprintf(out, "const int item_count = %d;\n", count);

    fclose(out);
    fclose(in);
    printf("make-items: wrote %d items to %s\n", count, argv[1]);
    return 0;
}
