#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Write docs/examples.md from the examples' own test.toml descriptions.

The catalogue is generated rather than written because every example already
carries a one-line description that CI reads, and a hand-maintained second
copy would be wrong within a release. Run it after adding an example:

    python scripts/gen_examples_index.py        # rewrite the page
    python scripts/gen_examples_index.py --check  # fail if it is out of date
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
PAGE = ROOT / "docs" / "examples.md"

HEADER = """# Examples

Every example below is a self-contained project with its own `pcons-build.py`,
built and verified on Linux, macOS and Windows on every commit — so each one is
both a worked answer and a guarantee that the feature still works.

Browse them at
[github.com/DarkStarSystems/pcons/tree/main/examples](https://github.com/DarkStarSystems/pcons/tree/main/examples),
or copy one and build it:

```bash
cd examples/01_hello_c
uvx pcons
```

<!-- Generated by scripts/gen_examples_index.py; edit the examples' test.toml
     descriptions instead. -->

| Example | What it shows |
|---|---|
"""


def describe(example: Path) -> str | None:
    """The example's own one-line description, or None if it has no test.toml."""
    config = example / "test.toml"
    if not config.is_file():
        return None
    data = tomllib.loads(config.read_text(encoding="utf-8"))
    description = data.get("test", {}).get("description", "")
    return description.strip() or None


def render() -> str:
    rows = []
    for example in sorted(EXAMPLES.iterdir()):
        if not example.is_dir():
            continue
        description = describe(example)
        if description is None:
            continue
        url = f"https://github.com/DarkStarSystems/pcons/tree/main/examples/{example.name}"
        # Escape the cell separator; descriptions are prose and may contain one.
        # Done before the f-string: a backslash inside one needs Python 3.12.
        cell = description.replace("|", "\\|")
        rows.append(f"| [`{example.name}`]({url}) | {cell} |")
    return HEADER + "\n".join(rows) + "\n"


def main(argv: list[str]) -> int:
    page = render()
    if "--check" in argv:
        current = PAGE.read_text(encoding="utf-8") if PAGE.exists() else ""
        if current != page:
            print(
                "docs/examples.md is out of date; "
                "run python scripts/gen_examples_index.py",
                file=sys.stderr,
            )
            return 1
        return 0
    PAGE.write_text(page, encoding="utf-8")
    print(f"wrote {PAGE.relative_to(ROOT)} ({page.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
