# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for Environment's tool namespaces and known variables.

GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.

Each toolchain registers its own subset of tools into `env._tools` at
setup time; there is no single runtime registry to introspect. The
tool list is therefore maintained in `_gen_stubs.py`. Adding a new
tool to a toolchain requires updating `_ENVIRONMENT_TOOL_NAMES` there.

Environment.__getattr__ is intentionally left visible to type checkers
(returning `Any`), so user-defined cross-tool variables like
`env.my_flag = ...` continue to work without a type:ignore. Known names
below are typed more specifically and take precedence."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pcons.core.toolconfig import ToolConfig

    class _EnvironmentStubs:
        """Typed mixin for Environment (TYPE_CHECKING-only)."""

        cc: ToolConfig  # C/C++ toolchains (gcc, llvm, msvc, clang_cl, emscripten, wasi)
        cxx: ToolConfig  # C/C++ toolchains
        ar: ToolConfig  # GCC/LLVM/emscripten/wasi/gfortran
        link: ToolConfig  # all C/C++ and Fortran toolchains
        lib: ToolConfig  # MSVC and clang-cl
        rc: ToolConfig  # MSVC and clang-cl (Windows resource compiler)
        ml: ToolConfig  # MSVC and clang-cl (assembler)
        mt: ToolConfig  # MSVC (manifest tool)
        metal: ToolConfig  # LLVM on macOS (Apple Metal shader compiler)
        fc: ToolConfig  # gfortran
        cuda: ToolConfig  # CUDA toolchain (added via env.add_toolchain)
        cython: ToolConfig  # Cython toolchain
        cycc: ToolConfig  # Cython toolchain
        cylink: ToolConfig  # Cython toolchain
        install: ToolConfig  # always set up via Environment._setup_standalone_tools
        archive: ToolConfig  # always set up via Environment._setup_standalone_tools
        build_dir: Path
        variant: str
