# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Built-in feature preset names accepted by `env.apply_preset(...)`.

GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.

Scraped from every toolchain's FEATURE_PRESETS. The Literal exists
purely for IDE completion and typo checking; plain `str` is also
accepted at runtime so contributed presets ('scope/name') resolve
normally. A name here may still be unavailable on a given system or
toolchain — guard optional features with `env.has_preset(name)`."""

from typing import Literal

KnownFeaturePreset = Literal[
    "coverage",  # EmscriptenToolchain, GccToolchain, GfortranToolchain, LlvmToolchain, WasiToolchain
    "fast-math",  # ClangClToolchain, EmscriptenToolchain, GccToolchain, GfortranToolchain, LlvmToolchain, MsvcToolchain, WasiToolchain
    "hardened",  # ClangClToolchain, EmscriptenToolchain, GccToolchain, LlvmToolchain, MsvcToolchain, WasiToolchain
    "lto",  # ClangClToolchain, EmscriptenToolchain, GccToolchain, LlvmToolchain, MsvcToolchain, WasiToolchain
    "openmp",  # ClangClToolchain, GccToolchain, GfortranToolchain, LlvmToolchain, MsvcToolchain
    "profile",  # ClangClToolchain, EmscriptenToolchain, GccToolchain, LlvmToolchain, MsvcToolchain, WasiToolchain
    "pthread",  # EmscriptenToolchain, GccToolchain, LlvmToolchain, WasiToolchain
    "sanitize",  # ClangClToolchain, EmscriptenToolchain, GccToolchain, LlvmToolchain, MsvcToolchain, WasiToolchain
    "warnings",  # ClangClToolchain, EmscriptenToolchain, GccToolchain, GfortranToolchain, LlvmToolchain, MsvcToolchain, SwiftToolchain, WasiToolchain
    "werror",  # ClangClToolchain, EmscriptenToolchain, GccToolchain, GfortranToolchain, LlvmToolchain, MsvcToolchain, SwiftToolchain, WasiToolchain
]
