# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for Project's built-in builder methods.

GENERATED by `python -m pcons._gen_stubs` from the BuilderRegistry. Do
not edit by hand — re-run the generator instead.

`Project` inherits from `_ProjectBuilders` only under TYPE_CHECKING (see
project.py). At runtime, `_ProjectBuilders = object` and builder lookup
falls through to `Project.__getattr__` as before. The methods here exist
solely so that type checkers (ty, pyright, mypy) can flag typos like
`project.Programx(...)` and provide completion. User-registered
`@builder` targets are not in this file; because Project's `__getattr__`
is hidden from type checkers, calls to them appear as unresolved
attributes and require a `type: ignore` / `ty: ignore` at the call site.
See examples/15_custom_builder for the canonical pattern.

The class body is nested under `if TYPE_CHECKING:` so that ty does not
treat the `def Foo(...) -> Target: ...` empty bodies as runtime errors;
type checkers see the declarations, runtime never executes them.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pcons.core.environment import Environment as Env
    from pcons.core.node import FileNode, Node
    from pcons.core.target import Target
    from pcons.tools.archive import ArchiveTarget

    class _ProjectBuilders:
        """Typed builder methods for Project (TYPE_CHECKING-only mixin)."""

        def Appx(
            self,
            env: Env,
            *,
            name: str,
            version: str,
            publisher: str,
            sources: list[Target | FileNode | Path | str],
            output: str | Path | None = None,
            display_name: str | None = None,
            description: str | None = None,
            processor_architecture: str = 'x64',
        ) -> Target:
            """Create a Windows AppX package (legacy MSIX format) [win32 only]"""
            ...

        def Command(
            self,
            name: str,
            env: Env,
            *,
            target: str | Path | list[str | Path],
            source: str | Path | list[str | Path] | None = None,
            command: str | list[str] = '',
        ) -> Target:
            """Create a custom command target."""
            ...

        def ComponentPkg(
            self,
            env: Env,
            *,
            identifier: str,
            version: str,
            sources: list[Target | FileNode | Path | str],
            install_location: str = '/Applications',
            output: str | Path | None = None,
            scripts_dir: Path | None = None,
            component_plist: Path | None = None,
            ownership: str = 'recommended',
            sign_identity: str | None = None,
        ) -> Target:
            """Create a macOS component package using pkgbuild [darwin only]"""
            ...

        def Dmg(
            self,
            env: Env,
            *,
            name: str,
            sources: list[Target | FileNode | Path | str],
            volume_name: str | None = None,
            output: str | Path | None = None,
            format: str = 'UDZO',
            applications_symlink: bool = True,
        ) -> Target:
            """Create a macOS .dmg disk image [darwin only]"""
            ...

        def FlatBundle(
            self,
            env: Env,
            plugin: Target,
            *,
            bundle_dir: Path | str,
            dlls: list[Target | Path | str] | None = None,
            resources: list[Path | str] | None = None,
        ) -> Target:
            """Create a flat directory bundle (cross-platform)"""
            ...

        def HeaderOnlyLibrary(
            self,
            name: str,
            include_dirs: list[str | Path] | None = None,
        ) -> Target:
            """Create a header-only (interface) library target."""
            ...

        def Install(
            self,
            dest_dir: Path | str,
            sources: Sequence[Target | FileNode | Path | str],
            *,
            name: str | None = None,
        ) -> Target:
            """Install files to a destination directory."""
            ...

        def InstallAs(
            self,
            dest: Path | str,
            source: Target | FileNode | Path | str,
            *,
            name: str | None = None,
        ) -> Target:
            """Install a file to a specific destination path."""
            ...

        def InstallDir(
            self,
            dest_dir: Path | str,
            source: Target | FileNode | Path | str,
            *,
            name: str | None = None,
        ) -> Target:
            """Install a directory tree to a destination."""
            ...

        def MacosBundle(
            self,
            env: Env,
            plugin: Target,
            *,
            bundle_dir: Path | str,
            info_plist: str | Path | None = None,
            resources: list[Path | str] | None = None,
            arch_subdir: str | None = None,
        ) -> Target:
            """Create a macOS .bundle or .plugin structure [darwin only]"""
            ...

        def Msix(
            self,
            env: Env,
            *,
            name: str,
            version: str,
            publisher: str,
            sources: list[Target | FileNode | Path | str],
            executable: str | None = None,
            output: str | Path | None = None,
            display_name: str | None = None,
            description: str | None = None,
            processor_architecture: str = 'x64',
            sign_cert: Path | None = None,
            sign_password: str | None = None,
        ) -> Target:
            """Create a Windows MSIX package [win32 only]"""
            ...

        def ObjectLibrary(
            self,
            name: str,
            env: Env,
            sources: list[str | Path | Node] | None = None,
        ) -> Target:
            """Create an object library target (compiles but doesn't link)."""
            ...

        def Pkg(
            self,
            env: Env,
            *,
            name: str,
            version: str,
            identifier: str,
            sources: list[Target | FileNode | Path | str],
            install_location: str = '/Applications',
            output: str | Path | None = None,
            title: str | None = None,
            welcome: Path | None = None,
            readme: Path | None = None,
            license: Path | None = None,
            conclusion: Path | None = None,
            background: Path | None = None,
            min_os_version: str | None = None,
            scripts_dir: Path | None = None,
            sign_identity: str | None = None,
        ) -> Target:
            """Create a macOS product archive (.pkg) installer [darwin only]"""
            ...

        def Program(
            self,
            name: str,
            env: Env,
            sources: list[str | Path | Node] | None = None,
        ) -> Target:
            """Create a program (executable) target."""
            ...

        def SharedLibrary(
            self,
            name: str,
            env: Env,
            sources: list[str | Path | Node] | None = None,
        ) -> Target:
            """Create a shared library target."""
            ...

        def StaticLibrary(
            self,
            name: str,
            env: Env,
            sources: list[str | Path | Node] | None = None,
        ) -> Target:
            """Create a static library target."""
            ...

        def Tarfile(
            self,
            env: Env,
            *,
            output: str | Path,
            sources: list[str | Path | FileNode | Target] | None = None,
            compression: str | None = None,
            base_dir: str | Path | None = None,
            name: str | None = None,
        ) -> ArchiveTarget:
            """Create a tar archive from source files/directories."""
            ...

        def Zipfile(
            self,
            env: Env,
            *,
            output: str | Path,
            sources: list[str | Path | FileNode | Target] | None = None,
            base_dir: str | Path | None = None,
            name: str | None = None,
        ) -> ArchiveTarget:
            """Create a zip archive from source files/directories."""
            ...
