# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for ToolConfig's well-known variables.

GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.

Variables under a tool namespace (`env.cc.flags`, `env.link.libs`, …)
are stored in a dict and accessed via __getattr__, which returns Any.
The names below cover the universal C/C++/link surface so editors can
type and complete the common operations. Toolchain-specific variables
continue to work via __getattr__ — that path stays visible to type
checkers so unusual names do not need `type: ignore`."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:

    class _ToolConfigStubs:
        """Typed mixin for ToolConfig (TYPE_CHECKING-only)."""

        cmd: str | list[Any]  # command template (string or token list)
        flags: list[Any]  # compile/link flags; can hold strings or subst tokens
        includes: list[Path | str]  # include directories
        defines: list[str]  # preprocessor defines, e.g. ['FOO=1']
        libs: list[Any]  # library names or Target/subst-token entries
        libdirs: list[Path | str]  # library search directories
        frameworks: list[str]  # macOS frameworks
        frameworkdirs: list[Path | str]  # macOS framework search dirs
        exe: str  # path to the tool executable
