# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Known toolchain names accepted by `Environment(toolchain=...)`.

GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.

Scraped from the toolchain registry: finder names (auto-detection
entry points like "c") and toolchain aliases (specific toolchains
like "gcc"). The Literal exists purely for IDE completion and typo
checking; plain `str` is also accepted at runtime so user-registered
toolchains resolve normally."""

from typing import Literal

KnownToolchain = Literal[
    "c",  # Auto-detect a C/C++ toolchain
    "c++",  # Auto-detect a C/C++ toolchain
    "clang",  # LLVM/Clang compiler
    "clang-cl",  # Clang with MSVC-compatible flags
    "cpp",  # Auto-detect a C/C++ toolchain
    "cuda",  # Auto-detect the NVIDIA CUDA toolchain (nvcc)
    "cython",  # Auto-detect the Cython toolchain
    "emcc",  # Emscripten C/C++ to WebAssembly + JS (browser/Node.js)
    "emscripten",  # Auto-detect the Emscripten WebAssembly toolchain
    "fortran",  # Auto-detect a Fortran toolchain
    "gcc",  # GNU Compiler Collection (gcc/g++)
    "gfortran",  # GNU Fortran compiler (gfortran)
    "gnu",  # GNU Compiler Collection (gcc/g++)
    "latex",  # LaTeX document compilation via latexmk
    "latexmk",  # LaTeX document compilation via latexmk
    "llvm",  # LLVM/Clang compiler
    "msvc",  # Microsoft Visual C/C++ compiler
    "nvcc",  # NVIDIA CUDA compiler (nvcc)
    "vc",  # Microsoft Visual C/C++ compiler
    "visualstudio",  # Microsoft Visual C/C++ compiler
    "wasi",  # Auto-detect the WASI SDK WebAssembly toolchain
    "wasi-sdk",  # WASI SDK for standalone WebAssembly (.wasm)
]
