# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for UsageRequirements's well-known fields.

GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.

`target.public.*` and `target.private.*` access values through
UsageRequirements.__getattr__, which returns `list` for any name.
The names below are the C/C++ conventional set. Toolchains can
invent any other names they need; those continue to work via
__getattr__ (kept visible to type checkers)."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from typing import MutableSequence
    from pcons.core.subst import PathToken
    from pcons.core.target import Target

    class _UsageRequirementsStubs:
        """Typed mixin for UsageRequirements (TYPE_CHECKING-only)."""

        include_dirs: MutableSequence[Path | str]  # directories added to dependents' include path
        compile_flags: MutableSequence[str | PathToken]  # flags propagated to dependents (strings, or PathToken for embedded paths)
        link_flags: MutableSequence[str | PathToken]  # flags propagated to dependents (strings, or PathToken for embedded paths)
        defines: MutableSequence[str]  # preprocessor defines propagated to dependents
        link_libs: MutableSequence[str | Target]  # link deps: a Target brings its public usage requirements (headers etc.); a str is a raw link token; public re-exports, private does not
