# SPDX-License-Identifier: MIT
# ruff: noqa
# fmt: off
"""Typed stub declarations for UsageRequirements's well-known fields.

GENERATED by `python -m pcons._gen_stubs`. Do not edit by hand.

`target.public.*` and `target.private.*` access values through
UsageRequirements.__getattr__, which returns `list` for any name.
The names below are the C/C++ conventional set. Toolchains can
invent any other names they need; those continue to work via
__getattr__ (kept visible to type checkers)."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:

    class _UsageRequirementsStubs:
        """Typed mixin for UsageRequirements (TYPE_CHECKING-only)."""

        include_dirs: list[Path | str]  # directories added to dependents' include path
        compile_flags: list[Any]  # flags propagated to dependents (strings + subst tokens)
        link_flags: list[Any]  # flags propagated to dependents (strings + subst tokens)
        defines: list[str]  # preprocessor defines propagated to dependents
        link_libs: list[Any]  # libraries propagated to dependents (str + Target + tokens)
